feat: support new browser Alipay MYWeb ua
faisalman/ua-parser-js pull request #631
Opened 2023-02-09 14:41 UTC by RaoHai

* MYWeb is a new browser kernel SDK in alipay. https://www.alipay.com/
* UA example: `Mozilla/5.0 (Linux; Android 10; VOG-AL00 Build/HUAWEIVOG-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.148 MYWeb/0.2.103.0_20230131112530 UWS/3.22.2.9999 UCBS/3.22.2.9999_220000000000 Mobile Safari/537.36 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:WIFI,ws:360|0|3.0) AliApp(AP/10.3.50.9999) AlipayClient/10.3.50.9999 Language/en isConcaveScreen/true Region/CN ProductType/devAriver/1.0.0` 
* test case

2023-02-27 00:51 UTC, RaoHai commented
Hello @faisalman, can you please review this pr and give some suggestions?

2023-03-27 01:07 UTC, faisalman commented
It would be better if the name could represent it's marketing name or publicly known name regardless it's SDK. Something like `Alipay` or `AliApp` might be a good candidate.

2023-09-30 07:23 UTC, faisalman requested changes
I prefer to expose the marketing name of the Apps

2023-10-02 11:58 UTC, faisalman commented
Since there are no more activity in this thread, I'll close this for a while

2023-10-02 11:58 UTC, closed without merging